def generate_tables(n):
    greet = "This table is generated by Python."
    tables = ""
    
    for i in range(1, 11):
        with open(f"tables/table_{n}", "w") as f:
            tables += f"{n} * {i} = {n * i}\n"
            f.write(f"{greet}\n\n{tables}")
   

for i in range(1, 21):
    generate_tables(i)